const fundwiseOutstandingHeader = {
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	fund_id: "Fund ID",
	fund_name: "Fund Name",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
}

const cowiseOutstandingHeader = {
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
	co_name: "CO Name",
}

const groupwiseOutstandingHeader = {
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	bank_name: "Bank Name",
	acc_no1: "Account No. 1",
	acc_no2: "Account No. 2",
	recovery_day: "Recovery Day",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
	co_name: "CO Name",
}

const memberwiseOutstandingHeader = {
	group_code: "Group Code",
	group_name: "Group Name",
	acc_no1: "Savings Account",
	acc_no2: "Loan Account",
	grp_addr: "Group Address",
	co_id: "CO ID",
	emp_name: "Employee Name",
	loan_id: "Loan ID",
	member_code: "Member Code",
	client_name: "Member Name",
	scheme_id: "Scheme ID",
	scheme_name: "Scheme Name",
	transaction_id: "Txn ID",
	transaction_date: "Txn Date",
	particulars: "Particulars",
	debit: "Debit",
	debit: "Debit",
	curr_balance: "Current Balance",
	created_code: "Created Code",
	created_at: "Created At",
	created_by: "Created By",
	approved_at: "Approved At",
	approved_code: "Approved Code",
	approved_by: "Approved By",
}

const disbursementDetailsHeader = {
	loan_id: "Loan ID",
	member_code: "Member Code",
	client_name: "Client Name",
	purpose: "Purpose",
	purpose_id: "Purpose Name",
	scheme_id: "Scheme ID",
	scheme_name: "Scheme Name",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	fund_id: "Fund ID",
	fund_name: "Fund Name",
	applied_amt: "Applied Amt",
	disburse_amt: "Disburse Amt",
	disb_dt: "Disburse Date",
	curr_outstanding: "Current Outstanding",
}

const branchwiseOutstandingHeader = {
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
}

const branchwiseTxnReportHeader = {
	branch_id: "Branch ID",
	branch_name: "Branch Name",
	debit: "Debit",
	curr_balance: "Current Balance",
}

const groupwiseDemandReportHeader = {
	demand_date: "Demand Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	co_name: "CO Name",
	disb_dt: "Disbursement Date",
	disb_amt: "Disbursement Amount",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	recovery_day: "Recovery Day",
	instl_start_dt: "Demand Start Date",
	instl_end_dt: "Demand End Date",
	tot_emi: "Total EMI",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	emp_name: "Employee Name",
	coll_amt: "Collection Amount",
	loan_period: "Loan Period",
	demand_after_collection: "Demand After Collection",
}

const fundwiseDemandReportHeader = {
	demand_date: "Demand Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	co_name: "CO Name",
	fund_id: "Fund ID",
	fund_name: "Fund Name",
	period_mode: "Period Mode",
	recovery_day: "Recovery Day",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	demand_after_collection: "Demand After Collection",
	coll_amt: "Collection Amount",
	emp_name: "Employee Name",
}

const cowiseDemandReportHeader = {
	demand_date: "Demand Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	co_name: "CO Name",
	period_mode: "Period Mode",
	recovery_day: "Recovery Day",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	collec_upto: "Collection Upto",
	emp_name: "Employee Name",
	tot_emi: "Total EMI",
	coll_amt: "Collection Amount",
	demand_after_collection: "Demand After Collection",
}

const memberwiseDemandReportHeader = {
	demand_date: "Demand Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	loan_id: "Loan ID",
	member_code: "Member Code",
	client_name: "Client Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	co_name: "CO Name",
	disb_dt: "Disbursement Date",
	disb_amt: "Disbursement Amount",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	instl_start_dt: "Demand Start Date",
	instl_end_dt: "Demand End Date",
	tot_emi: "Total EMI",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	coll_amt: "Collection Amount",
	demand_after_collection: "Demand After Collection",
}

const branchwiseDemandReportHeader = {
	demand_date: "Demand Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	collec_upto: "Collected Upto",
}

const overduereportheader = {
	trf_date: "Report Date",
	first_od_date: "OD Date",
	branch_code: "Branch Code",
	branch_name: "Branch Name",
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO Name",
	disb_dt: "Disbursement Date",
	disb_amt: "Disbursement Amount",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	recovery_day: "Recovery Day",
	instl_start_dt: "Demand Start Date",
	instl_end_dt: "Demand End Date",
	tot_emi: "Total EMI",
	demand_amt: "Demand Amount",
	curr_outstanding: "Current Outstanding",
	emp_name: "Employee Name",
	coll_amt: "Collection Amount",
	loan_period: "Loan Period",
	od_amt:'OD Amount',
	demand_after_collection: "Demand After Collection",
}

const transactionFieldNames = {
	transaction_date: "Transaction Date",
	transaction_id: "Transaction ID",
	loan_id: "Loan ID",
	tr_type: "Transaction Type",
	debit: "Debit Amount",
	credit: "Credit Amount",
	created_code: "Created Branch Code",
	created_by: "Created By",
  }

export {
	fundwiseOutstandingHeader,
	cowiseOutstandingHeader,
	groupwiseOutstandingHeader,
	memberwiseOutstandingHeader,
	disbursementDetailsHeader,
	branchwiseOutstandingHeader,
	branchwiseTxnReportHeader,
	groupwiseDemandReportHeader,
	fundwiseDemandReportHeader,
	cowiseDemandReportHeader,
	memberwiseDemandReportHeader,
	branchwiseDemandReportHeader,
	overduereportheader,
	transactionFieldNames
}
