const fundwiseOutstandingHeader = {
	group_code: "Group Code",
	group_name: "Group Name",
	fund_id: "Fund ID",
	fund_name: "Fund Name",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
}

const cowiseOutstandingHeader = {
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
	co_name: "CO Name",
}

const groupwiseOutstandingHeader = {
	group_code: "Group Code",
	group_name: "Group Name",
	co_id: "CO ID",
	bank_name: "Bank Name",
	acc_no1: "Account No. 1",
	acc_no2: "Account No. 2",
	recovery_day: "Recovery Day",
	prn_disb_amt: "Disbursement Amt",
	prn_outstanding: "Outstanding Principal",
	intt_outstanding: "Outstanding Interest",
	outstanding: "Outstanding",
	co_name: "CO Name",
}

const memberwiseOutstandingHeader = {
	group_code: "Group Code",
	group_name: "Group Name",
	acc_no1: "Savings Account",
	acc_no2: "Loan Account",
	grp_addr: "Group Address",
	co_id: "CO ID",
	emp_name: "Employee Name",
	loan_id: "Loan ID",
	member_code: "Member Code",
	client_name: "Member Name",
	scheme_id: "Scheme ID",
	scheme_name: "Scheme Name",
	transaction_id: "Txn ID",
	transaction_date: "Txn Date",
	particulars: "Particulars",
	debit: "Debit",
	debit: "Debit",
	curr_balance: "Current Balance",
	created_code: "Created Code",
	created_at: "Created At",
	created_by: "Created By",
	approved_at: "Approved At",
	approved_code: "Approved Code",
	approved_by: "Approved By",
}

const disbursementDetailsHeader = {
	loan_id: "Loan ID",
	member_code: "Member Code",
	client_name: "Client Name",
	purpose: "Purpose",
	purpose_id: "Purpose Name",
	scheme_id: "Scheme ID",
	scheme_name: "Scheme Name",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	fund_id: "Fund ID",
	fund_name: "Fund Name",
	applied_amt: "Applied Amt",
	disburse_amt: "Disburse Amt",
	disb_dt: "Disburse Date",
	curr_outstanding: "Current Outstanding",
}

const loanStatementHeaderMemberwise = {
	trans_date: "Txn Date",
	trans_no: "Txn ID",
	Particulars: "Particulars",
	credit: "Credit",
	debit: "Debit",
	bank_charge: "Bank Charge",
	proc_charge: "Processing Charge",
	prn_recov: "Principal Recovery",
	intt_recov: "Interest Recovery",
	prn_bal: "Principal Balance",
	intt_bal: "Interest Balance",
	total_outstanding: "Total Outstanding",
	tr_type: "Transaction Type",
	tr_mode: "Transaction Mode",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	tot_emi: "Total EMI",
}

const loanStatementHeaderGroupwise = {
	trans_date: "Txn Date",
	particulars: "Particulars",
	tr_type: "Transaction Type",
	debit: "Debit",
	credit: "Credit",
	bank_charge: "Bank Charge",
	proc_charge: "Processing Charge",
	balance: "Balance",
	curr_roi: "Current ROI",
	period: "Period",
	period_mode: "Period Mode",
	tot_emi: "Total EMI",
}

export {
	fundwiseOutstandingHeader,
	cowiseOutstandingHeader,
	groupwiseOutstandingHeader,
	memberwiseOutstandingHeader,
	disbursementDetailsHeader,
	loanStatementHeaderMemberwise,
	loanStatementHeaderGroupwise
}
